name: "br-meshtastic: luckfox_pico"

on:
  workflow_dispatch:

jobs:
  mksys:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "RV1103_Luckfox_Pico"
            lunch_board: "0"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1103_Luckfox_Pico_Mini_A"
            lunch_board: "1"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1103_Luckfox_Pico_Mini_B"
            lunch_board: "2"
            lunch_boot_medium: "1"  # eMMC
            # include/wind.h is missing for Pico Plus?
          - name: "RV1103_Luckfox_Pico_Plus"
            lunch_board: "3"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1106_Luckfox_Pico_Pro"
            lunch_board: "4"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1106_Luckfox_Pico_Max"
            lunch_board: "5"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1106_Luckfox_Pico_Ultra"
            lunch_board: "6"
            lunch_boot_medium: "0"  # SD Card
          - name: "RV1106_Luckfox_Pico_Ultra_W"
            lunch_board: "7"
            lunch_boot_medium: "0"  # SD Card

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "20G"
          create-symlink: true
          key: ${{ matrix.name }}

      - name: Create Timestamp
        run: |
              echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
              echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Checkout luckfox-pico Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/luckfox-pico'
            path: 'luckfox_pico_sdk'
            ref: 'vid_testing'  # vidplace7 branch

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Add Toolchain to PATH
        shell: bash
        run: |
              echo "$GITHUB_WORKSPACE/luckfox_pico_sdk/bin" >> $GITHUB_PATH
              echo "$GITHUB_WORKSPACE/luckfox_pico_sdk/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin" >> $GITHUB_PATH

      - name: Setup board config (lunch)
        shell: expect {0}
        working-directory: ./luckfox_pico_sdk
        # luckfox sdk forces an interactive shell, so we need to use expect
        run: |
              spawn ./build.sh lunch

              expect "Lunch menu...pick the Luckfox Pico hardware version:"
              sleep 0.5
              send "${{ matrix.lunch_board }}\r"
              expect "Lunch menu...pick the boot medium:"
              sleep 0.5
              send "${{ matrix.lunch_boot_medium }}\r"
              expect "Lunch menu...pick the system version"
              sleep 0.5
              send "0\r"
              expect eof

      - name: Build Info
        shell: bash
        working-directory: ./luckfox_pico_sdk
        run: |
              ./build.sh info

      - name: Buildroot Config
        shell: expect {0}
        working-directory: ./luckfox_pico_sdk
        env:
          TERM: xterm
          BR2_EXTERNAL: ${{ github.workspace }}/external
        # luckfox sdk forces an ncurses menu, so we need to use expect and a pseudo terminal
        run: |
              spawn script -q -c "./build.sh buildrootconfig" /dev/null
              expect "< Exit >"
              sleep 0.5
              send "E"
              expect eof

      # - name: Cache Buildroot
      #   id: cache-buildroot
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       luckfox_pico_sdk/sysdrv/source/buildroot/buildroot-*/dl
      #     key: br-${{ matrix.name }}

      - name: Make System
        shell: bash
        working-directory: ./luckfox_pico_sdk
        run: |
              ./build.sh

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: "buildroot-meshtastic-${{ matrix.name }}-${{ github.run_number }}.${{ github.run_attempt }}"
          path: |
                  luckfox_pico_sdk/IMAGE/IPC_*/*
          if-no-files-found: error
