name: "build: luckfox_pico"

on:
  # workflow_dispatch:

  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "Board name"
      lunch_board:
        required: true
        type: string
        description: "luckfox_sdk lunch board"
      lunch_boot_medium:
        required: true
        type: string
        description: "luckfox_sdk lunch boot medium"

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"
          create-symlink: true
          key: ${{ inputs.name }}

      - name: Checkout luckfox-pico Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/luckfox-pico'
            path: 'luckfox_pico_sdk'
            ref: 'vid_testing'  # vidplace7 branch

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Add Toolchain to PATH
        shell: bash
        run: |
              echo "$GITHUB_WORKSPACE/luckfox_pico_sdk/bin" >> $GITHUB_PATH
              echo "$GITHUB_WORKSPACE/luckfox_pico_sdk/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin" >> $GITHUB_PATH

      - name: Setup board config (lunch)
        shell: expect {0}
        working-directory: ./luckfox_pico_sdk
        # luckfox sdk forces an interactive shell, so we need to use expect
        run: |
              spawn ./build.sh lunch

              expect "Lunch menu...pick the Luckfox Pico hardware version:"
              sleep 0.5
              send "${{ inputs.lunch_board }}\r"
              expect "Lunch menu...pick the boot medium:"
              sleep 0.5
              send "${{ inputs.lunch_boot_medium }}\r"
              expect "Lunch menu...pick the system version"
              sleep 0.5
              send "0\r"
              expect eof

      - name: Build Info
        shell: bash
        working-directory: ./luckfox_pico_sdk
        run: |
              ./build.sh info

      - name: Buildroot Config
        shell: expect {0}
        working-directory: ./luckfox_pico_sdk
        env:
          TERM: xterm
          BR2_EXTERNAL: ${{ github.workspace }}/external
        # luckfox sdk forces an ncurses menu, so we need to use expect and a pseudo terminal
        run: |
              spawn script -q -c "./build.sh buildrootconfig" /dev/null
              expect "< Exit >"
              sleep 0.5
              send "E"
              expect eof

      - name: Make System
        shell: bash
        working-directory: ./luckfox_pico_sdk
        run: |
              echo "Building Images"
              ./build.sh

      - name: Package Images
        shell: bash
        working-directory: ./luckfox_pico_sdk/output/image
        run: |
              echo "Setting up tools"
              cp $GITHUB_WORKSPACE/external/build/bin/blkenvflash ./blkenvflash
              chmod +x ./blkenvflash
              echo "Packaging combined image"
              ./blkenvflash buildroot-meshtastic-${{ inputs.name }}-${{ github.run_number }}.${{ github.run_attempt }}.img

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: "buildroot-meshtastic-${{ inputs.name }}-${{ github.run_number }}.${{ github.run_attempt }}"
          path: |
                  luckfox_pico_sdk/output/image/**
          if-no-files-found: error
          include-hidden-files: true
