name: "br-meshtastic: licheerv_nano"

on:
  workflow_dispatch:

jobs:
  mksys:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "LicheeRV Nano RISC-V"
            cvi_defconfig: "sg2002_licheervnano_sd"
            br_defconfig: "cvitek_SG200X_musl_riscv64_defconfig"
          # - name: "LicheeRV Nano ARM"
          #   cvi_defconfig: "sg2002_licheea53nano_sd"
          #   br_defconfig: "cvitek_SG200X_32bit_defconfig"

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "20G"
          create-symlink: true
          key: licheerv_${{ matrix.cvi_defconfig }}

      - name: Create Timestamp
        run: |
              echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
              echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Checkout LicheeRV-Nano-Build Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/LicheeRV-Nano-Build'
            path: 'cvi_mmf_sdk'
            ref: 'licheervnano'  # markbirss branch

      - name: Checkout sophgo host-tools
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/sophgo-host-tools'
            path: 'cvi_mmf_sdk/host-tools'
            ref: 'meshtastic'

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Cache Buildroot
        id: cache-buildroot
        uses: actions/cache@v4
        with:
          path: |
            cvi_mmf_sdk/buildroot/dl
          key: br-licheerv_${{ matrix.cvi_defconfig }}

      - name: Make System
        shell: bash
        working-directory: ./cvi_mmf_sdk
        run: |
              source build/cvisetup.sh
              defconfig ${{ matrix.cvi_defconfig }}
              make -C buildroot/ BR2_EXTERNAL=$GITHUB_WORKSPACE/external ${{ matrix.br_defconfig }} BR2_TOOLCHAIN_EXTERNAL_PATH=$CROSS_COMPILE_PATH
              build_all

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: "buildroot-meshtastic-${{ matrix.cvi_defconfig }}"
          path: |
                  cvi_mmf_sdk/install/soc_${{ matrix.cvi_defconfig }}/images/*
                  cvi_mmf_sdk/install/soc_${{ matrix.cvi_defconfig }}/*.bin
          if-no-files-found: error
