name: "build: raspberrypi"

on:
  # workflow_dispatch:

  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "Board friendly name"
      defconfig:
        required: true
        type: string
        description: "buildroot defconfig"

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"
          create-symlink: true
          key: ${{ inputs.defconfig }}

      - name: Checkout Buildroot Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot/buildroot'
            path: 'buildroot'
            ref: '2024.08.x'

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Make System
        shell: bash
        working-directory: ./buildroot
        env:
          BR2_EXTERNAL: ${{ github.workspace }}/external
          FORCE_UNSAFE_CONFIGURE: "1"  # Bypass warning about root user, this is a container!
        run: |
              make ${{ inputs.defconfig }}_defconfig
              make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: "buildroot-meshtastic-${{ inputs.defconfig }}-${{ github.run_number }}.${{ github.run_attempt }}"
          path: |
                  buildroot/output/images/**
          if-no-files-found: error
