name: "br-meshtastic: licheerv_nano"

on:
  workflow_dispatch:

jobs:
  mksys:
    strategy:
      fail-fast: false

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    # env:
    #   BR2_EXTERNAL: ${{ github.workspace }}/external

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "20G"
          create-symlink: true
          key: ${{ runner.os }}

      - name: Create Timestamp
        run: |
              echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
              echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Checkout LicheeRV-Nano-Build Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/LicheeRV-Nano-Build'
            path: 'cvi_mmf_sdk'
            ref: 'vid_testing'

      - name: Checkout sophgo host-tools
        uses: actions/checkout@v4
        with:
            repository: 'buildroot-meshtastic/sophgo-host-tools'
            path: 'cvi_mmf_sdk/host-tools'
            ref: 'meshtastic'

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Make System
        shell: bash
        working-directory: ./cvi_mmf_sdk
        run: |
              source build/cvisetup.sh
              defconfig sg2002_licheervnano_sd
              make -C buildroot/ BR2_EXTERNAL=$GITHUB_WORKSPACE/external cvitek_SG200X_musl_riscv64_defconfig BR2_TOOLCHAIN_EXTERNAL_PATH=$CROSS_COMPILE_PATH
              build_all

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: buildroot-meshtastic-licheerv_nano-${{ env.BUILD_ID }}
          path: |
                  cvi_mmf_sdk/install/soc_sg2002_licheervnano_sd/images/*
                  cvi_mmf_sdk/install/soc_sg2002_licheervnano_sd/*.bin
          if-no-files-found: error
