name: "br-meshtastic: raspberrypi"

on:
  workflow_dispatch:

jobs:
  mksys:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "RPi Zero"
            defconfig: "raspberrypi0"

          - name: "RPi Zero W"
            defconfig: "raspberrypi0w"

          - name: "RPi Zero 2 W"
            defconfig: "raspberrypizero2w"

    runs-on: [ self-hosted, linux ]
    container: ghcr.io/buildroot-meshtastic/buildroot-meshtastic-builder:main

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"
          create-symlink: true
          key: ${{ matrix.defconfig }}

      - name: Checkout Buildroot Repo
        uses: actions/checkout@v4
        with:
            repository: 'buildroot/buildroot'
            path: 'buildroot'
            ref: '2024.08.x'

      - name: Checkout this Repo to 'external'
        uses: actions/checkout@v4
        with:
            path: 'external'

      - name: Make System
        shell: bash
        working-directory: ./buildroot
        env:
          BR2_EXTERNAL: ${{ github.workspace }}/external
          FORCE_UNSAFE_CONFIGURE: "1"  # Bypass warning about root user, this is a container!
        run: |
              make ${{ matrix.defconfig }}_defconfig
              make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          compression-level: 9
          name: "buildroot-meshtastic-${{ matrix.defconfig }}-${{ github.run_number }}.${{ github.run_attempt }}"
          path: |
                  buildroot/output/images/**
          if-no-files-found: error
