name: "build_all: luckfox_pico"

on:
  workflow_dispatch:

jobs:
  mksys:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "RV1103_Luckfox_Pico"
            lunch_board: "0"
            lunch_boot_medium: "0"  # SD_CARD

          - name: "RV1103_Luckfox_Pico_Mini_A"
            lunch_board: "1"
            lunch_boot_medium: "0"  # SD_CARD

          #   # Mini_B Fails to create filesystem
          # - name: "RV1103_Luckfox_Pico_Mini_B"
          #   lunch_board: "2"
          #   lunch_boot_medium: "1"  # SPI_NAND

          - name: "RV1103_Luckfox_Pico_Plus"
            lunch_board: "3"
            lunch_boot_medium: "0"  # SD_CARD

          - name: "RV1106_Luckfox_Pico_Pro"
            lunch_board: "4"
            lunch_boot_medium: "0"  # SD_CARD

          - name: "RV1106_Luckfox_Pico_Max"
            lunch_board: "5"
            lunch_boot_medium: "0"  # SD_CARD

          - name: "RV1106_Luckfox_Pico_Ultra"
            lunch_board: "6"
            lunch_boot_medium: "0"  # EMMC

          - name: "RV1106_Luckfox_Pico_Ultra_W"
            lunch_board: "7"
            lunch_boot_medium: "0"  # EMMC

    uses: ./.github/workflows/build-luckfox_pico.yml
    with:
        name: ${{ matrix.name }}
        lunch_board: ${{ matrix.lunch_board }}
        lunch_boot_medium: ${{ matrix.lunch_boot_medium }}
